#!/bin/bash

# A non-default bridge network enables convenient name-to-hostname discovery
docker network create kafka-net

docker run -d --name zookeeper --network kafka-net zookeeper:3.4
docker run -d --name kafka --network kafka-net --env ZOOKEEPER_IP=zookeeper ches/kafka

docker run --rm --network kafka-net ches/kafka kafka-topics.sh --create --topic test --replication-factor 1 --partitions 1 --zookeeper zookeeper:2181

# In separate terminals:
#docker run --rm -it --interactive --network kafka-net ches/kafka kafka-console-producer.sh --topic test --broker-list kafka:9092

#docker run --rm -it --network kafka-net ches/kafka kafka-console-consumer.sh --topic test --from-beginning --bootstrap-server kafka:9092

docker run --rm -it --network kafka-net ksolaima/kafka-producer
docker run --rm -it --network kafka-net ksolaima/kafka-producer-

docker build -t ksolaima/kafka-consumer .
# docker run --rm -p 8000:6000 --network kafka-net ksolaima/kafka-consumer
