version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
    - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
    - "9092:9092"
    container_name: kafka-broker
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  producer:
    image: ksolaima/twitter-kafka
    command: python extract_tweets_restful.py
    #stdin_open: true
    #tty: true
    ports:
    - "5000"
    depends_on:
    - kafka
  #consumer:
    #image: ksolaima/kafka-consumer
    ##ports:
    ##- "6000"
    #depends_on:
    #- kafka
    #- producer
    #stdin_open: true
    #tty: true
